@echo off
echo Starting NKBot Godfather Protocol...
echo [1/2] Starting API Backend...
start "NKBot Brain" cmd /k "cd .. && python -m uvicorn src.api:app --reload --host 0.0.0.0 --port 8000"

echo [2/2] Starting Web Dashboard...
echo Waiting for backend...
timeout /t 5
npm run dev
